language: node_js
node_js:
  - '12'
cache:
  - yarn
  directories: - node_modules
services:
  - mysql
before_install:
  - cd server
before_script:
  - mysql -u root -e 'CREATE DATABASE $DATABASE_NAME;'
  - mysql -u root -e "CREATE USER '$DATABASE_USERNAME'@'$DATABASE_HOST' IDENTIFIED BY '$DATABASE_PASSWORD';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON $DATABASE_NAME.* TO '$DATABASE_USERNAME'@'$DATABASE_HOST';"
  - yarn install -g typescript
  - yarn link typescript
script:
  - yarn test-server &
  - yarn test
